FetchReach-v1: &fetch-defaults
  n_timesteps: !!float 1e5
  policy: 'MultiInputPolicy'
  buffer_size: 1000000
  ent_coef: 0.01
  batch_size: 256
  gamma: 0.95
  learning_rate: 0.001
  learning_starts: 1000
  normalize: True
  replay_buffer_class: HerReplayBuffer
  replay_buffer_kwargs: "dict(
    online_sampling=True,
    goal_selection_strategy='future',
    n_sampled_goal=4
  )"
  policy_kwargs: "dict(net_arch=[64, 64])"

FetchPush-v1:
  <<: *fetch-defaults
  n_timesteps: !!float 5e6
  policy_kwargs: "dict(net_arch=[512, 512])"

FetchSlide-v1:
  <<: *fetch-defaults
  n_timesteps: !!float 5e6
  policy_kwargs: "dict(net_arch=[512, 512])"

FetchPickAndPlace-v1:
  <<: *fetch-defaults
  n_timesteps: !!float 5e6
  policy_kwargs: "dict(net_arch=[512, 512])"
